begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|providers
operator|.
name|oauth2
operator|.
name|google
package|;
end_package

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|jackson
operator|.
name|JsonNode
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|providers
operator|.
name|oauth2
operator|.
name|OAuth2AuthUser
import|;
end_import

begin_class
specifier|public
class|class
name|GoogleAuthUser
extends|extends
name|OAuth2AuthUser
block|{
comment|/** 	 * From https://developers.google.com/accounts/docs/OAuth2Login#userinfocall 	 */
specifier|public
specifier|static
class|class
name|Constants
block|{
specifier|public
specifier|static
specifier|final
name|String
name|ID
init|=
literal|"id"
decl_stmt|;
comment|// "00000000000000",
specifier|public
specifier|static
specifier|final
name|String
name|EMAIL
init|=
literal|"email"
decl_stmt|;
comment|// "fred.example@gmail.com",
specifier|public
specifier|static
specifier|final
name|String
name|EMAIL_IS_VERIFIED
init|=
literal|"verified_email"
decl_stmt|;
comment|// true,
specifier|public
specifier|static
specifier|final
name|String
name|NAME
init|=
literal|"name"
decl_stmt|;
comment|// "Fred Example",
specifier|public
specifier|static
specifier|final
name|String
name|FIRST_NAME
init|=
literal|"given_name"
decl_stmt|;
comment|// "Fred",
specifier|public
specifier|static
specifier|final
name|String
name|LAST_NAME
init|=
literal|"family_name"
decl_stmt|;
comment|// "Example",
specifier|public
specifier|static
specifier|final
name|String
name|PICTURE
init|=
literal|"picture"
decl_stmt|;
comment|// "https://lh5.googleusercontent.com/-2Sv-4bBMLLA/AAAAAAAAAAI/AAAAAAAAABo/bEG4kI2mG0I/photo.jpg",
specifier|public
specifier|static
specifier|final
name|String
name|GENDER
init|=
literal|"gender"
decl_stmt|;
comment|// "male",
specifier|public
specifier|static
specifier|final
name|String
name|LOCALE
init|=
literal|"locale"
decl_stmt|;
comment|// "en-US"
block|}
specifier|public
name|GoogleAuthUser
parameter_list|(
specifier|final
name|JsonNode
name|n
parameter_list|,
specifier|final
name|GoogleAuthInfo
name|info
parameter_list|)
block|{
name|super
argument_list|(
name|n
operator|.
name|get
argument_list|(
name|Constants
operator|.
name|ID
argument_list|)
operator|.
name|asText
argument_list|()
argument_list|,
name|info
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getProvider
parameter_list|()
block|{
return|return
name|GoogleAuthProvider
operator|.
name|PROVIDER_KEY
return|;
block|}
block|}
end_class

end_unit

