begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|controllers
package|;
end_package

begin_import
import|import
name|play
operator|.
name|mvc
operator|.
name|Call
import|;
end_import

begin_import
import|import
name|play
operator|.
name|mvc
operator|.
name|Controller
import|;
end_import

begin_import
import|import
name|play
operator|.
name|mvc
operator|.
name|Result
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|PlayAuthenticate
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|exceptions
operator|.
name|AccessDeniedException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|exceptions
operator|.
name|AccessTokenException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|exceptions
operator|.
name|AuthException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|providers
operator|.
name|AuthProvider
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|user
operator|.
name|AuthUser
import|;
end_import

begin_class
specifier|public
class|class
name|AuthenticateController
extends|extends
name|Controller
block|{
specifier|public
specifier|static
name|Result
name|authenticate
parameter_list|(
specifier|final
name|String
name|provider
parameter_list|)
block|{
specifier|final
name|AuthProvider
name|ap
init|=
name|AuthProvider
operator|.
name|Registry
operator|.
name|get
argument_list|(
name|provider
argument_list|)
decl_stmt|;
if|if
condition|(
name|ap
operator|==
literal|null
condition|)
block|{
comment|// Provider wasn't found and/or user was fooling with our stuff - tell him off:
return|return
name|notFound
argument_list|()
return|;
block|}
try|try
block|{
specifier|final
name|Object
name|o
init|=
name|ap
operator|.
name|authenticate
argument_list|(
name|ctx
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|o
operator|instanceof
name|String
condition|)
block|{
return|return
name|redirect
argument_list|(
operator|(
name|String
operator|)
name|o
argument_list|)
return|;
block|}
elseif|else
if|if
condition|(
name|o
operator|instanceof
name|AuthUser
condition|)
block|{
specifier|final
name|AuthUser
name|u
init|=
operator|(
name|AuthUser
operator|)
name|o
decl_stmt|;
comment|// We might want to do merging here:
comment|// Adapted from:
comment|// http://stackoverflow.com/questions/6666267/architecture-for-merging-multiple-user-accounts-together
comment|// 1. The account is linked to a local account and no session
comment|// cookie is present --> Login
comment|// 2. The account is linked to a local account and a session
comment|// cookie is present --> Merge
comment|// 3. The account is not linked to a local account and no
comment|// session cookie is present --> Signup
comment|// 4. The account is not linked to a local account and a session
comment|// cookie is present --> Linking Additional account
specifier|final
name|boolean
name|isLoggedIn
init|=
name|PlayAuthenticate
operator|.
name|isLoggedIn
argument_list|(
name|session
argument_list|()
argument_list|)
decl_stmt|;
specifier|final
name|Object
name|loginIdentity
init|=
name|PlayAuthenticate
operator|.
name|getUserService
argument_list|()
operator|.
name|getLocalIdentity
argument_list|(
name|u
argument_list|)
decl_stmt|;
specifier|final
name|boolean
name|isLinked
init|=
name|loginIdentity
operator|!=
literal|null
decl_stmt|;
specifier|final
name|AuthUser
name|loginUser
decl_stmt|;
if|if
condition|(
name|isLinked
operator|&&
operator|!
name|isLoggedIn
condition|)
block|{
comment|// 1. -> Login
name|loginUser
operator|=
name|u
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|isLinked
operator|&&
name|isLoggedIn
condition|)
block|{
comment|// 2. -> Merge
comment|// get the user with which we are logged in - is null if we
comment|// are
comment|// not logged in
specifier|final
name|AuthUser
name|oldUser
init|=
name|PlayAuthenticate
operator|.
name|getUser
argument_list|(
name|ctx
argument_list|()
argument_list|)
decl_stmt|;
comment|// merge the two identities and return the AuthUser we want
comment|// to use for the log in
if|if
condition|(
name|PlayAuthenticate
operator|.
name|isAccountMergeEnabled
argument_list|()
operator|&&
operator|!
name|loginIdentity
operator|.
name|equals
argument_list|(
name|PlayAuthenticate
operator|.
name|getUserService
argument_list|()
operator|.
name|getLocalIdentity
argument_list|(
name|oldUser
argument_list|)
argument_list|)
condition|)
block|{
comment|// account merge is enabled
comment|// and
comment|// The currently logged in user and the one to log in
comment|// are not the same, so shall we merge?
if|if
condition|(
name|PlayAuthenticate
operator|.
name|isAccountAutoMerge
argument_list|()
condition|)
block|{
comment|// Account auto merging is enabled
name|loginUser
operator|=
name|PlayAuthenticate
operator|.
name|getUserService
argument_list|()
operator|.
name|merge
argument_list|(
name|u
argument_list|,
name|oldUser
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// Account auto merging is disabled - forward user
comment|// to merge request page
specifier|final
name|Call
name|c
init|=
name|PlayAuthenticate
operator|.
name|getResolver
argument_list|()
operator|.
name|askMerge
argument_list|()
decl_stmt|;
if|if
condition|(
name|c
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Merge controller not defined, even though accountAutoMerge is set to false"
argument_list|)
throw|;
block|}
name|PlayAuthenticate
operator|.
name|storeMergeUser
argument_list|(
name|u
argument_list|,
name|session
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|redirect
argument_list|(
name|c
argument_list|)
return|;
block|}
block|}
else|else
block|{
comment|// the currently logged in user and the new login belong
comment|// to the same local user,
comment|// or Account merge is disabled, so just change the log
comment|// in to the new user
name|loginUser
operator|=
name|u
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
operator|!
name|isLinked
operator|&&
operator|!
name|isLoggedIn
condition|)
block|{
comment|// 3. -> Signup
name|loginUser
operator|=
name|PlayAuthenticate
operator|.
name|signupUser
argument_list|(
name|u
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// !isLinked&& isLoggedIn:
comment|// 4. -> Link additional
if|if
condition|(
name|PlayAuthenticate
operator|.
name|isAccountAutoLink
argument_list|()
condition|)
block|{
comment|// Account auto linking is enabled
comment|// get the user with which we are logged in - is null if
comment|// we are
comment|// not logged in
specifier|final
name|AuthUser
name|oldUser
init|=
name|PlayAuthenticate
operator|.
name|getUser
argument_list|(
name|ctx
argument_list|()
argument_list|)
decl_stmt|;
name|loginUser
operator|=
name|PlayAuthenticate
operator|.
name|getUserService
argument_list|()
operator|.
name|link
argument_list|(
name|oldUser
argument_list|,
name|u
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// Account auto linking is disabled - forward user to
comment|// link suggestion page
specifier|final
name|Call
name|c
init|=
name|PlayAuthenticate
operator|.
name|getResolver
argument_list|()
operator|.
name|askLink
argument_list|()
decl_stmt|;
if|if
condition|(
name|c
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Link controller not defined, even though accountAutoLink is set to false"
argument_list|)
throw|;
block|}
name|PlayAuthenticate
operator|.
name|storeLinkUser
argument_list|(
name|u
argument_list|,
name|session
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|redirect
argument_list|(
name|c
argument_list|)
return|;
block|}
block|}
return|return
name|PlayAuthenticate
operator|.
name|loginAndRedirect
argument_list|(
name|ctx
argument_list|()
argument_list|,
name|loginUser
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|internalServerError
argument_list|(
literal|"Something went wrong"
argument_list|)
return|;
block|}
block|}
catch|catch
parameter_list|(
specifier|final
name|AuthException
name|e
parameter_list|)
block|{
if|if
condition|(
name|e
operator|instanceof
name|AccessTokenException
condition|)
block|{
return|return
name|internalServerError
argument_list|(
literal|"Exchanging request token for access token failed"
argument_list|)
return|;
block|}
elseif|else
if|if
condition|(
name|e
operator|instanceof
name|AccessDeniedException
condition|)
block|{
return|return
name|forbidden
argument_list|(
name|e
operator|.
name|getMessage
argument_list|()
argument_list|)
return|;
block|}
return|return
name|internalServerError
argument_list|(
name|e
operator|.
name|getMessage
argument_list|()
argument_list|)
return|;
block|}
block|}
block|}
end_class

end_unit

