begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|service
package|;
end_package

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|providers
operator|.
name|AuthUser
import|;
end_import

begin_import
import|import
name|com
operator|.
name|feth
operator|.
name|play
operator|.
name|module
operator|.
name|pa
operator|.
name|providers
operator|.
name|AuthUserIdentity
import|;
end_import

begin_interface
specifier|public
interface|interface
name|UserService
block|{
comment|/** 	 * generates a user identity from an auth provider/id combination 	 *  	 * @param provider 	 * @param id 	 * @return 	 */
specifier|public
name|AuthUserIdentity
name|find
parameter_list|(
specifier|final
name|String
name|provider
parameter_list|,
specifier|final
name|String
name|id
parameter_list|)
function_decl|;
comment|/** 	 * Saves auth provider/id combination to a local user 	 * @param authUser 	 * @return 	 */
specifier|public
name|Long
name|save
parameter_list|(
specifier|final
name|AuthUser
name|authUser
parameter_list|)
function_decl|;
comment|/** 	 * Returns true if the auth provider/id combination has been linked to a local user account already 	 * @param identity 	 * @return 	 */
specifier|public
name|boolean
name|isLinked
parameter_list|(
specifier|final
name|AuthUserIdentity
name|identity
parameter_list|)
function_decl|;
comment|/** 	 * Merges two user accounts after a login with an auth provider/id that is linked to a different account than the login from before 	 * Returns the user to generate the session information from 	 *  	 * @param newUser 	 * @param oldUser 	 * @return 	 */
specifier|public
name|AuthUser
name|merge
parameter_list|(
specifier|final
name|AuthUser
name|newUser
parameter_list|,
specifier|final
name|AuthUser
name|oldUser
parameter_list|)
function_decl|;
comment|/** 	 * Links a new account to an exsting local user. 	 * Returns the auth user to log in with 	 *  	 * @param oldUser 	 * @param newUser 	 */
specifier|public
name|AuthUser
name|link
parameter_list|(
specifier|final
name|AuthUser
name|oldUser
parameter_list|,
specifier|final
name|AuthUser
name|newUser
parameter_list|)
function_decl|;
block|}
end_interface

end_unit

